### ISSUE TITLE
Editor doesn't load

### ISSUE THREAD

**Issue by FezVrasta** [asikart/ace-markdown-editor#20]
Hi,

I was trying your editor on Joomla 3.3.6, I've installed it and enabled the system plugin. Then I've set the editor as default.

When I try to write an article the editor is not loaded but just a simple textarea is opened.

No errors are reported on the javascript console nor on the PHP errors log...

Any solution?

**Comment by asika32764** [comment]
Check the editor plugin enabled or not.

AKMarkdown will not appear textarea if JS error, the ACE editor does not use textarea to contain text, so I think the editor plugin not work.

**Comment by FezVrasta** [comment]
Both parts are enabled and no errors are reported in JavaScript console...

![image](https://cloud.githubusercontent.com/assets/5382443/6187952/c33af5fe-b38c-11e4-8e79-6f85d824a3b3.png)

**Comment by FezVrasta** [comment]
Ok suddenly it started working, that's weird :) Maybe there was some bottleneck...

**Comment by asika32764** [comment]
:+1: 

It think it's maybe caused by some browser script cache

**Comment by FezVrasta** [comment]
By the way it doesn't work inside html modules so it's kinda useless for me :(

**Comment by asika32764** [comment]
Do you mean it not render markdown of this module on frontend?

Try enabled `Prepare Content`

![p-2015-02-13-5](https://cloud.githubusercontent.com/assets/1639206/6188048/96c2597c-b3c8-11e4-9748-f46e659f0d86.jpg)

**Comment by FezVrasta** [comment]
Thanks but it doesn't work even with this option enabled. 

![image](https://cloud.githubusercontent.com/assets/5382443/6188166/d1cbcb14-b38e-11e4-9530-e46af04eb94c.png)

**Comment by asika32764** [comment]
Works on my test site

![p-2015-02-13-7](https://cloud.githubusercontent.com/assets/1639206/6188236/126f7aea-b3ca-11e4-8562-18c44ad7e69f.jpg)

![p-2015-02-13-6](https://cloud.githubusercontent.com/assets/1639206/6188237/12912046-b3ca-11e4-97d5-d1ba9b03d5fe.jpg)

Has the cache disabled?

**Comment by FezVrasta** [comment]
No it's not disabled but neither the preview works.
![image](https://cloud.githubusercontent.com/assets/5382443/6188318/500e11ac-b390-11e4-8b98-767a7e073c93.png)

**Comment by asika32764** [comment]
Maybe it is a syntax error.

Could you paste your markdown code?

**Comment by FezVrasta** [comment]
Yes trying with just a simple text `**test**` it works.. But using it inside my HTML code doesn't work... 

Markdown is thought to be used along with HTML so I wonder why it doesn't work.


```````html
<div class="rt-effect-border">
	<img src="http://maps.google.com/maps/api/staticmap?center=45.621618,9.474273&zoom=13&markers=45.621618,9.474273&size=1000x480&sensor=false" alt="image"><div class="rt-effect-content">
		<h2><a href="/negozi" class="fp-demo-url"><span>Negozi</span></a></h2>
		<p class="visible-desktop"><a href="#" class="fp-demo-url">Trova i nostri **punti** vendita</a></p>
	</div>			
</div>
<div class="gantry-width-container">
	<div class="gantry-width-33">
		<a href="https://www.facebook.com/emisferosud.bijoux">
			<div class="rt-icon-1">
				<i class="fa fa-facebook fa-3x"></i>
			</div>
		</a>
	</div>
	<div class="gantry-width-33">
		<a href="https://twitter.com/emisfero_sud">
			<div class="rt-icon-2">
				<i class="fa fa-twitter fa-3x"></i>
			</div>
		</a>
	</div>
	<div class="gantry-width-33">
		<a href="https://www.pinterest.com/emisferosud/">
			<div class="rt-icon-3">
				<i class="fa fa-pinterest fa-3x"></i>
			</div>
		</a>
	</div>		
</div>
````````````

**Comment by asika32764** [comment]
Yes, you cannot has a markdown code inside `<a>` tags.

But the PHP MarkdownExtra support markdown code inside some tags included `<div>`.

Please see: https://michelf.ca/projects/php-markdown/extra/

**Comment by FezVrasta** [comment]
I've the markdown extra feature enabled in the system plugin...
Isn't it enough?

![image](https://cloud.githubusercontent.com/assets/5382443/6188470/a184b01c-b391-11e4-9921-651d9d9e66d6.png)

**Comment by asika32764** [comment]
Maybe still not works in `<a>` tag, I think it is markdown rules.

**Comment by FezVrasta** [comment]
I don't think so...

<a href=#>**just a** test</a>

On github it works, on stackexchange as well

**Comment by asika32764** [comment]
GitHub has their own markdown rule, it called GitHub flavored Markdown:
https://help.github.com/articles/github-flavored-markdown/

The raw markdown please see this: 
http://daringfireball.net/projects/markdown/syntax

**Comment by FezVrasta** [comment]
Ok I see

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.

It's a shame, I need this plugin just to allow the owner of the website to edit html modules without have to write html tags... Thanks anyway

**Comment by asika32764** [comment]
You're welcome
