### ISSUE TITLE
Editor Window Obscured

### ISSUE THREAD

**Issue by JamesHaskell** [asikart/ace-markdown-editor#28]
I've installed your Joomla plugin into a new Joomla site (Joomla version 3.4.3), and switched the default editor to ACE X Markdown, and enabled the second plugin.  Now whenever I edit content, I'm seeing a green opaque box, containing the text "lt editor", in the top left corner of every edit window.  It obscures the top 7 to 8 characters of the first two lines.  How do I make this go away?  See the attached screen shot.

![ace_editor_issue](https://cloud.githubusercontent.com/assets/2438362/9183181/8eb1235a-3f62-11e5-8342-cfe6260a9ae8.png)

**Comment by JamesHaskell** [comment]
I think I found the issue... there's a conflict with JSN's Pagebuilder.  Disabling the PageBuilder plugins made the spurious image disappear.

**Comment by asika32764** [comment]
:+1:
